version: "3.8"

services:
  # Add the frontend service
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./client
        target: /srv/app
    tty: true

  # Add the backend service
  node_backend:
    image: node:alpine
    container_name: node_backend
    ports:
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./backend  # Chemin vers votre application Node.js (backend)
        target: /srv/app
    command: npm start  # Commande pour démarrer votre serveur Node.js

  # Add the platform PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: root
    ports:
      - "8080:80"
