version: "3.4"

#Front-end container
services:
 vite_docker:
   image: node:alpine
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true

   #Back-end container
 mysql:
    container_name: database
    image: mysql:latest
    command: --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d