version: "3.8"

services:
  # Add the frontend service
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./client
        target: /srv/app
    tty: true


  # Add the platform PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: root
    ports:
      - "8080:80"

  # Add the MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"